{{- if .Values.metrics.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "k8s-watcher.fullname" . }}-metrics
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "metrics.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "metrics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metrics.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "k8s-watcher.serviceAccountName" . }}
      initContainers:
        - name: init-metrics
          image: "{{ .Values.metrics.init.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - name: configuration
              mountPath: /etc/komodor
      containers:
        - name: metrics
          image: {{ .Values.metrics.repository }} 
          volumeMounts:
            - name: {{ include "k8s-watcher.name" . }}-metrics-config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
          resources:
            {{- toYaml .Values.metrics.resources | nindent 12 }}
          envFrom:
          - configMapRef:
              name:  {{ .Values.watcher.metrics.varsConfigMapName }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
        - name: {{ include "k8s-watcher.name" . }}-metrics-config
          configMap:
            name: telegraf-metrics-config
        - name: configuration
          configMap:
            name: {{ include "k8s-watcher.name" . }}-config
            items:
              - key: komodor-k8s-watcher.yaml
                path: komodor-k8s-watcher.yaml
{{- end }}