apiVersion: v1
name: k8s-watcher
description: Watches and send kubernetes resource-related events
icon: https://raw.githubusercontent.com/komodorio/helm-charts/master/placeholder-logo.png
version: 1.0.3
appVersion: 0.1.135
