apiVersion: v1
name: k8s-watcher
description: Watches and send kubernetes resource-related events
icon: https://raw.githubusercontent.com/komodorio/helm-charts/master/k8s-watcher.svg
version: 1.0.11
appVersion: 0.1.141
